### ISSUE TITLE
How to contribute as maintainer

### ISSUE THREAD

**Issue by puhuk** [pmeier/pmeier#4]
Hi, 
This is puhuk used to contribute to pytorch/vision repository, thanks for your kind review and correcting my PR.
I'm not sure it is right way to ask this kind of question, but I open this issue because I think you are the right person to answer my question.

One of my long-term goal is to contribute as a maintainer to impactful open source projects like pytorch :)

Could you recommend any methods or stuffs to practice or study, or anything to start.

Thanks for your contribution :)
Best,

**Comment by pmeier** [comment]
Hey @puhuk :wave: Just dropping in to say that it will probably take me some time to answer since I'm on PTO. I'll probably get to it early next week.

**Comment by puhuk** [comment]
Thanks for the update! Please answer when you have time :)

**Comment by pmeier** [comment]
Hey @puhuk and sorry that I forgot about this. 

> One of my long-term goal is to contribute as a maintainer to impactful open source projects like pytorch :)

That is a noble goal and I'm happy you want to go this way :100:. We need to differentiate between two archetypes of OSS projects here:

1. Community driven and
2. organization driven.

Community driven projects is what most people think of if they hear OSS. Projects like `numpy` fall into that category. They are characterized that there is no "final instance" that dictates the way of the project or if there is it is usually elected by the community. 

In contrast, organization driven projects such as PyTorch are usually backed by a corporation that is paying developers to work on the project. Since they are paying they also get to dictate the direction of the project. That means despite being OSS, users of PyTorch have no say what will be included or left out in case Meta (the company behind PyTorch) decides otherwise. Of course unless there is a very good reason to do so they won't flat out reject proposal a lot of users want, but the whole project serves their internal needs first. If the external and internal needs conflict, the internal needs will take priority.

For your question this unfortunately means that becoming a maintainer of an organization driven project is nigh impossible without either working for the organization or another company contracted by the project organization (that is what I'm doing). The `torchvision` maintainers are working full time on this project and thus it is very hard to keep up with the time or communication needs that comes with this.

Of course this doesn't mean you can't bring impactful contributions.

> Could you recommend any methods or stuffs to practice or study, or anything to start.

IMO, the best way to contribute to OSS projects in the beginning is monitor the issue tracker. There are a few things you can do specifically:

- Look for issues labeled as [`help wanted`](is:issue is:open label:"help wanted" ) or [`good first issue`](is:issue is:open label:"good first issue" ) and try to tackle them. With these labels, we maintainers believe that someone new to the project is able to help us out there. In case something is not clear or you need additional pointers or help, feel free to ask. Remember that you are trying to help us, so giving you a helping hand in this task is the least we can do.
- If you are a user of the project yourself, ask yourself if you have encountered any issues or inconsistencies. Search through the issue tracker to see if they are already documented and otherwise open a new issue. Whether or not the issue already exist, make sure that it is actionable. Something like "X is not working" is rarely helpful.
- Try to solve small issues. Sometimes people just get confused on the basics and open an issue that should rather be a question in the user discussion forum. For example pytorch/vision#5795 or pytorch/vision#5686. This helps us maintainers big time, because it frees more time to solve issues that actually need our attention.

Over time you will get more insights how the project works and then you can pick up more complex tasks.

Hope this helps. Let me know if you additional guidance.

**Comment by puhuk** [comment]
@pmeier Thanks! It really helps :)
