### ISSUE TITLE
torchvision

### ISSUE THREAD

**Issue by taner45** [pmeier/pmeier#9]
Hello Philip,
 Is there a feature in torchvision that tiles my big pictures into small pieces (256,256) and merges them after sending them "OCR"? If not, can you help me with this?

thanks in advance

**Comment by pmeier** [comment]
Hey @taner45 :wave:

You can "tile" with the [`unfold`](https://pytorch.org/docs/stable/generated/torch.Tensor.unfold.html) operation. Here is a [small utility](https://github.com/pystiche/pystiche/blob/main/pystiche/core/_utils.py#L27-L35) to extract patches that I've used in on of my projects:

```python
import torch

def extract_patchesnd(
    input, patch_sizes, strides
) -> torch.Tensor:
    batch_size, num_channels = input.size()[:2]
    dims = range(2, input.dim())
    for dim, patch_size, stride in zip(dims, patch_sizes, strides):
        input = input.unfold(dim, patch_size, stride)
    return input.permute(0, *dims, 1, *[dim + len(dims) for dim in dims]).reshape(batch_size, -1, num_channels, *patch_sizes)

large_image = torch.rand(1, 3, 3_000, 4_000)

print(large_image.shape)

tiled_image = extract_patchesnd(
    large_image,
    # size of the tiles you want to have 
    patch_sizes=(256, 256),
    # if you want no overlap, this needs to be the same as patch_sizes
    strides=(256, 256),
)

print(tiled_image.shape)
```

```
torch.Size([1, 3, 3000, 4000])
torch.Size([1, 165, 3, 256, 256])
```

Meaning, we turned one large image with 4000x3000 pixels into 165 ones of size 256x256.

Hope this helps. However, I'm going to close this, since I can't provide user support here. If this is in relation to a PyTorch project that you are running, you can ask for help in the [user forum](https://discuss.pytorch.org).
